# Generated by Django 4.1.7 on 2023-02-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_update', models.DateTimeField(auto_created=True, verbose_name='Последнее обновление')),
                ('vcode', models.CharField(blank=True, max_length=150, null=True, verbose_name='Артикул')),
                ('name', models.CharField(blank=True, max_length=600, null=True, verbose_name='Наименование')),
                ('old_name', models.CharField(blank=True, max_length=600, null=True, verbose_name='Старое наименование')),
                ('brand', models.CharField(blank=True, max_length=300, null=True, verbose_name='Производитель')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
